### ISSUE TITLE
FizzBuzzWoof Samples

### ISSUE THREAD

**Issue by geleouet** [JosePaumard/JosePaumard.github.io#1]
1535 => FizzBuzzBuzzFizzBuzz (divisible by 3, divisible by 5, contains a 5, then a 3, then a 5)

1535 is not divisible by 3

I usually change it to 2535

**Comment by JosePaumard** [comment]
Oops, you're right, let me change that.

**Comment by JosePaumard** [comment]
The typo is now fixed, thank you!

**Comment by geleouet** [comment]
You're welcome, thx for sharing the kata
